/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    tailwindcss: {
      config: "./tailwind.config.ts",
      cssPath: "./src/styles/globals.css",
      content: ["./src/**/*.{js,ts,jsx,tsx}"],
      extract: {
        include: ["./src/**/*.{js,ts,jsx,tsx}"],
        exclude: ["./node_modules", "./src/styles/**/*.css"],
      },
      cssPath: "./src/styles/globals.css",
      cssMinify: true,
      cssVariables: true,
      cssVariablesOptions: {
        variables: {
          "primary-color": "#000",
          "secondary-color": "#fff",
          "tertiary-color": "#ccc",
          "quaternary-color": "#999",
          "quinary-color": "#666",
          "senary-color": "#333",
          "septenary-color": "#000",
          "octonary-color": "#fff",
          "nonary-color": "#ccc",
          "denary-color": "#999",
          "primary-font": "Arial, sans-serif",
          "secondary-font": "Helvetica, sans-serif",
          "tertiary-font": "Verdana, sans-serif",
          "quaternary-font": "Georgia, serif",
          "quinary-font": "Times New Roman, serif",
          "senary-font": "Palatino, serif",
          "septenary-font": "Bookman, serif",
          "octonary-font": "Garamond, serif",
          "nonary-font": "Baskerville, serif",
          "denary-font": "Caslon, serif",
          "primary-font-size": "16px",
          "secondary-font-size": "14px",
          "tertiary-font-size": "12px",
          "quaternary-font-size": "10px",
          "quinary-font-size": "8px",
          "senary-font-size": "6px",
          "septenary-font-size": "4px",
          "octonary-font-size": "2px",
          "nonary-font-size": "1px",
          "denary-font-size": "0.5px",
          "primary-font-weight": "normal",
          "secondary-font-weight": "bold",
          "tertiary-font-weight": "lighter",
          "quaternary-font-weight": "bolder",
          "quinary-font-weight": "lighter",
          "senary-font-weight": "bolder",
          "septenary-font-weight": "normal",
          "octonary-font-weight": "bold",
          "nonary-font-weight": "lighter",
          "denary-font-weight": "bolder",
          "primary-font-style": "normal",
          "secondary-font-style": "italic",
          "tertiary-font-style": "oblique",
          "quaternary-font-style": "normal",
          "quinary-font-style": "italic",
          "senary-font-style": "oblique",
          "septenary-font-style": "normal",
          "octonary-font-style": "italic",
          "nonary-font-style": "oblique",
          "denary-font-style": "normal",
          "primary-line-height": "1.5",
          "secondary-line-height": "1.5",
          "tertiary-line-height": "1.5",
          "quaternary-line-height": "1.5",
          "quinary-line-height": "1.5",
          "senary-line-height": "1.5",
          "septenary-line-height": "1.5",
          "octonary-line-height": "1.5",
          "nonary-line-height": "1.5",
          "denary-line-height": "1.5",
          "primary-letter-spacing": "0.1em",
          "secondary-letter-spacing": "0.1em",
          "tertiary-letter-spacing": "0.1em",
          "quaternary-letter-spacing": "0.1em",
          "quinary-letter-spacing": "0.1em",
          "senary-letter-spacing": "0.1em",
          "septenary-letter-spacing": "0.1em",
          "octonary-letter-spacing": "0.1em",
          "nonary-letter-spacing": "0.1em",
          "denary-letter-spacing": "0.1em",
          "primary-text-align": "left",
          "secondary-text-align": "center",
          "tertiary-text-align": "right",
          "quaternary-text-align": "justify",
          "quinary-text-align": "left",
          "senary-text-align": "center",
          "septenary-text-align": "right",
          "octonary-text-align": "justify",
          "nonary-text-align": "left",
          "denary-text-align": "center",
          "primary-text-decoration": "none",
          "secondary-text-decoration": "underline",
          "tertiary-text-decoration": "overline",
          "quaternary-text-decoration": "line-through",
          "quinary-text-decoration": "underline",
          "senary-text-decoration": "overline",
          "septenary-text-decoration": "line-through",
          "octonary-text-decoration": "underline",
          "nonary-text-decoration": "overline",
          "denary-text-decoration": "line-through",
          "primary-text-transform": "none",
          "secondary-text-transform": "uppercase",
          "tertiary-text-transform": "lowercase",
          "quaternary-text-transform": "capitalize",
          "quinary-text-transform": "none",
          "senary-text-transform": "uppercase",
          "septenary-text-transform": "lowercase",
          "octonary-text-transform": "capitalize",
          "nonary-text-transform": "none",
          "denary-text-transform": "uppercase",
          "primary-text-shadow": "none",
          "secondary-text-shadow": "1px 1px 1px #000",
          "tertiary-text-shadow": "2px 2px 2px #000",
          "quaternary-text-shadow": "3px 3px 3px #000",
          "quinary-text-shadow": "4px 4px 4px #000",
          "senary-text-shadow": "5px 5px 5px #000",
          "septenary-text-shadow": "6px 6px 6px #000",
          "octonary-text-shadow": "7px 7px 7px #000",
          "nonary-text-shadow": "8px 8px 8px #000",
          "denary-text-shadow": "9px 9px 9px #000",
          "primary-background-color": "#fff",
          "secondary-background-color": "#000",
          "tertiary-background-color": "#ccc",
          "quaternary-background-color": "#999",
          "quinary-background-color": "#666",
          "senary-background-color": "#333",
          "septenary-background-color": "#000",
          "octonary-background-color": "#fff",
          "nonary-background-color": "#ccc",
          "denary-background-color": "#999",
          "primary-background-image": "none",
          "secondary-background-image": "url('https://example.com/image.jpg')",
          "tertiary-background-image": "linear-gradient(to right, #000, #fff)",
          "quaternary-background-image": "radial-gradient(circle, #000, #fff)",
          "quinary-background-image": "repeating-linear-gradient(to right, #000, #fff, #000)",
          "senary-background-image": "repeating-radial-gradient(circle, #000, #fff, #000)",
          "septenary-background-image": "repeating-conic-gradient(from 0deg, #000, #fff, #000)",
          "octonary-background-image": "repeating-conic-gradient(from 45deg, #000, #fff, #000)",
          "nonary-background-image": "repeating-conic-gradient(from 90deg, #000, #fff, #000)",
          "denary-background-image": "repeating-conic-gradient(from 135deg, #000, #fff, #000)",
          "primary-background-size": "cover",
          "secondary-background-size": "contain",
          "tertiary-background-size": "auto",
          "quaternary-background-size": "auto",
          "quinary-background-size": "auto",
          "senary-background-size": "auto",
          "septenary-background-size": "auto",
          "octonary-background-size": "auto",
          "nonary-background-size": "auto",
          "denary-background-size": "auto",
          "primary-background-position": "center",
          "secondary-background-position": "top left",
          "tertiary-background-position": "bottom right",
          "quaternary-background-position": "center center",
          "quinary-background-position": "top left",
          "senary-background-position": "bottom right",
          "septenary-background-position": "center center",
          "octonary-background-position": "top left",
          "nonary-background-position": "bottom right",
          "denary-background-position": "center center",
          "primary-background-repeat": "no-repeat",
          "secondary-background-repeat": "repeat",
          "tertiary-background-repeat": "repeat-x",
          "quaternary-background-repeat": "repeat-y",
          "quinary-background-repeat": "repeat-space",
          "senary-background-repeat": "repeat-round",
          "septenary-background-repeat": "repeat-space",
          "octonary-background-repeat": "repeat-round",
          "nonary-background-repeat": "repeat-space",
          "denary-background-repeat": "repeat-round",
          "primary-background-attachment": "scroll",
          "secondary-background-attachment": "fixed",
          "tertiary-background-attachment": "local",
          "quaternary-background-attachment": "scroll",
          "quinary-background-attachment": "fixed",
          "senary-background-attachment": "local",
          "septenary-background-attachment": "scroll",
          "octonary-background-attachment": "fixed",
          "nonary-background-attachment": "local",
          "denary-background-attachment": "scroll",
          "primary-background-blend-mode": "normal",
          "secondary-background-blend-mode": "multiply",
          "tertiary-background-blend-mode": "screen",
          "quaternary-background-blend-mode": "overlay",
          "quinary-background-blend-mode": "darken",
          "senary-background-blend-mode": "lighten",
          "septenary-background-blend-mode": "color-dodge",
          "octonary-background-blend-mode": "color-burn",
          "nonary-background-blend-mode": "hard-light",
          "denary-background-blend-mode": "soft-light",
          "primary-border-color": "#000",
          "secondary-border-color": "#fff",
          "tertiary-border-color": "#ccc",
          "quaternary-border-color": "#999",
          "quinary-border-color": "#666",
          "senary-border-color": "#333",
          "septenary-border-color": "#000",
          "octonary-border-color": "#fff",
          "nonary-border-color": "#ccc",
          "denary-border-color": "#999",
          "primary-border-width": "1px",
          "secondary-border-width": "2px",
          "tertiary-border-width": "3px",
          "quaternary-border-width": "4px",
          "quinary-border-width": "5px",
          "senary-border-width": "6px",
          "septenary-border-width": "7px",
          "octonary-border-width": "8px",
          "nonary-border-width": "9px",
          "denary-border-width": "10px",
          "primary-border-style": "solid",
          "secondary-border-style": "dashed",
          "tertiary-border-style": "dotted",
          "quaternary-border-style": "double",
          "quinary-border-style": "groove",
          "senary-border-style": "ridge",
          "septenary-border-style": "inset",
          "octonary-border-style": "outset",
          "nonary-border-style": "hidden",
          "denary-border-style": "initial",
          "primary-border-radius": "0",
          "secondary-border-radius": "50%",
          "tertiary-border-radius": "10px",
          "quaternary-border-radius": "20px",
          "quinary-border-radius": "30px",
          "senary-border-radius": "40px",
          "septenary-border-radius": "50px",
          "octonary-border-radius": "60px",
          "nonary-border-radius": "70px",
          "denary-border-radius": "80px",
          "primary-border-image": "none",
          "secondary-border-image": "url('https://example.com/image.jpg')",
          "tertiary-border-image": "linear-gradient(to right, #000, #fff)",
          "quaternary-border-image": "radial-gradient(circle, #000, #fff)",
          "quinary-border-image": "repeating-linear-gradient(to right, #000, #fff, #000)",
          "senary-border-image": "repeating-radial-gradient(circle, #000, #fff, #000)",
          "septenary-border-image": "repeating-conic-gradient(from 0deg, #000, #fff, #000)",
          "octonary-border-image": "repeating-conic-gradient(from 45deg, #000, #fff, #000)",
          "nonary-border-image": "repeating-conic-gradient(from 90deg, #000, #fff, #000)",
          "denary-border-image": "repeating-conic-gradient(from 135deg, #000, #fff, #000)",
          "primary-border-image-source": "none",
          "secondary-border-image-source": "url('https://example.com/image.jpg')",
          "tertiary-border-image-source": "linear-gradient(to right, #000, #fff)",
          "quaternary-border-image-source": "radial-gradient(circle, #000, #fff)",
          "quinary-border-image-source": "repeating-linear-gradient(to right, #000, #fff, #000)",
          "senary-border-image-source": "repeating-radial-gradient(circle, #000, #fff, #000)",
          "septenary-border-image-source": "repeating-conic-gradient(from 0deg, #000, #fff, #000)",
          "octonary-border-image-source": "repeating-conic-gradient(from 45deg, #000, #fff, #000)",
          "nonary-border-image-source": "repeating-conic-gradient(from 90deg, #000, #fff, #000)",
          "denary-border-image-source": "repeating-conic-gradient(from 135deg, #000, #fff, #000)",
          "primary-border-image-slice": "100%",
          "secondary-border-image-slice": "100%",
          "tertiary-border-image-slice": "100%",
          "quaternary-border-image-slice": "100%",
          "quinary-border-image-slice": "100%",
          "senary-border-image-slice": "100%",
          "septenary-border-image-slice": "100%",
          "octonary-border-image-slice": "100%",
          "nonary-border-image-slice": "100%",
          "denary-border-image-slice": "100%",
          "primary-border-image-width": "100%",
          "secondary-border-image-width": "100%",
          "tertiary-border-image-width": "100%",
          "quaternary-border-image-width": "100%",
          "quinary-border-image-width": "100%",
          "senary-border-image-width": "100%",
          "septenary-border-image-width": "100%",
          "octonary-border-image-width": "100%",
          "nonary-border-image-width": "100%",
          "denary-border-image-width": "100%",
          "primary-border-image-outset": "0",
          "secondary-border-image-outset": "0",
          "tertiary-border-image-outset": "0",
          "quaternary-border-image-outset": "0",
          "quinary-border-image-outset": "0",
          "senary-border-image-outset": "0",
          "septenary-border-image-outset": "0",
          "octonary-border-image-outset": "0",
          "nonary-border-image-outset": "0",
          "denary-border-image-outset": "0",
          "primary-border-image-repeat": "stretch",
          "secondary-border-image-repeat": "repeat",
          "tertiary-border-image-repeat": "space",
          "quaternary-border-image-repeat": "round",
          "quinary-border-image-repeat": "space",
          "senary-border-image-repeat": "round",
          "septenary-border-image-repeat": "space",
          "octonary-border-image-repeat": "round",
          "nonary-border-image-repeat": "space",
          "denary-border-image-repeat": "round",
          "primary-box-shadow": "none",
          "secondary-box-shadow": "1px 1px 1px #000",
          "tertiary-box-shadow": "2px 2px 2px #000",
          "quaternary-box-shadow": "3px 3px 3px #000",
          "quinary-box-shadow": "4px 4px 4px #000",
          "senary-box-shadow": "5px 5px 5px #000",
          "septenary-box-shadow": "6px 6px 6px #000",
          "octonary-box-shadow": "7px 7px 7px #000",
          "nonary-box-shadow": "8px 8px 8px #000",
          "denary-box-shadow": "9px 9px 9px #000",
          "primary-opacity": "1",
          "secondary-opacity": "0.5",
          "tertiary-opacity": "0.25",
          "quaternary-opacity": "0.125",
          "quinary-opacity": "0.0625",
          "senary-opacity": "0.03125",
          "septenary-opacity": "0.015625",
          "octonary-opacity": "0.0078125",
          "nonary-opacity": "0.00390625",
          "denary-opacity": "0.001953125",
          "primary-transform": "none",
          "secondary-transform": "translateX(10px)",
          "tertiary-transform": "translateY(-10px)",
          "quaternary-transform": "translateZ(10px)",
          "quinary-transform": "scale(1.1)",
          "senary-transform": "scale(0.9)",
          "septenary-transform": "rotate(15deg)",
          "octonary-transform": "rotate(-15deg)",
          "nonary-transform": "skew(10deg, 10deg)",
          "denary-transform": "skew(-10deg, -10deg)",
          "primary-transition": "all 0.3s ease",
          "secondary-transition": "color 0.3s ease",
          "tertiary-transition": "background-color 0.3s ease",
          "quaternary-transition": "border-color 0.3s ease",
          "quinary-transition": "border-width 0.3s ease",
          "senary-transition": "border-style 0.3s ease",
          "septenary-transition": "border-radius 0.3s ease",
          "octonary-transition": "border-image 0.3s ease",
          "nonary-transition": "box-shadow 0.3s ease",
          "denary-transition": "opacity 0.3s ease",
          "primary-animation": "none",
          "secondary-animation": "slideIn 1s ease-in-out",
          "tertiary-animation": "fadeIn 1s ease-in-out",
          "quaternary-animation": "rotate 1s linear infinite",
          "quinary-animation": "bounce 1s ease-in-out infinite",
          "senary-animation": "flash 1s ease-in-out infinite",
          "septenary-animation": "pulse 1s ease-in-out infinite",
          "octonary-animation": "shake 1s ease-in-out infinite",
          "nonary-animation": "wobble 1s ease-in-out infinite",
          "denary-animation": "swing 1s ease-in-out infinite"
        },
      },
    },
  },
};

export default config;
